'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { toast } from 'sonner';
import { Share2, Link2, Check } from 'lucide-react';
import { cn } from '@/lib/utils';

// Platform logos aren't in lucide-react; inlined to match the sign-in page's
// Google icon pattern.
function XIcon({ className }: { className?: string }) {
  return (
    <svg viewBox="0 0 24 24" className={className} fill="currentColor" aria-hidden="true">
      <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
    </svg>
  );
}

function LinkedInIcon({ className }: { className?: string }) {
  return (
    <svg viewBox="0 0 24 24" className={className} fill="currentColor" aria-hidden="true">
      <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.446-2.136 2.94v5.666H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 1 1 0-4.125 2.062 2.062 0 0 1 0 4.125zM7.119 20.452H3.554V9h3.565v11.452z" />
    </svg>
  );
}

function RedditIcon({ className }: { className?: string }) {
  return (
    <svg viewBox="0 0 24 24" className={className} fill="currentColor" aria-hidden="true">
      <path d="M12 0C5.373 0 0 5.373 0 12c0 3.314 1.343 6.314 3.515 8.485l-2.286 2.286C.775 23.225 1.097 24 1.738 24H12c6.627 0 12-5.373 12-12S18.627 0 12 0zm5.5 12.75a1.5 1.5 0 0 1-2.302 1.267c-1.02.63-2.334 1.024-3.759 1.076l.641-3.017 2.083.443a1 1 0 1 0 .128-.63l-2.335-.497a.5.5 0 0 0-.593.386l-.719 3.385c-1.44-.043-2.77-.438-3.799-1.07a1.5 1.5 0 1 1 1.582-2.528 4.982 4.982 0 0 1 1.478-.67l.583-2.742a.5.5 0 0 1 .593-.386l2.606.554a1 1 0 1 1-.128.63l-2.213-.47-.485 2.284c.54.075 1.05.22 1.516.42a1.497 1.497 0 0 1 2.678.938c0 .12-.011.238-.033.352.117.166.178.365.178.575zm-7.75 0a.75.75 0 1 1 1.5 0 .75.75 0 0 1-1.5 0zm4 2.25c-.69 0-1.32-.128-1.865-.35a.25.25 0 0 1 .19-.462c.46.19 1.008.3 1.675.3.667 0 1.216-.11 1.676-.3a.25.25 0 0 1 .19.462c-.546.222-1.176.35-1.866.35zm1.25-2.25a.75.75 0 1 1 1.5 0 .75.75 0 0 1-1.5 0z" />
    </svg>
  );
}

type ShareTarget = {
  key: string;
  label: string;
  icon: (props: { className?: string }) => JSX.Element;
  href: string;
};

/**
 * Share a Need or product publicly (X, LinkedIn, Reddit, copy link). `text`
 * is the pre-filled X/Reddit post copy -- generated by the caller from the
 * real title/description so it always matches, never hardcoded here.
 *
 * `layout="dropdown"` (default) is a single compact trigger, used in a
 * detail page's action bar. `layout="row"` renders all four as individual
 * visible buttons, used in a post-submit success state where sharing is
 * the primary next action, not a secondary menu item.
 */
export function ShareButtons({
  url,
  text,
  redditTitle,
  label = 'Share',
  variant = 'outline',
  layout = 'dropdown',
  onShare,
}: {
  url: string;
  text: string;
  /**
   * Reddit post title -- defaults to `text`'s first line, which is only
   * correct when the caller's `text` leads with the real title (true for
   * product share text, not for Need share text, which leads with a generic
   * intro line). Pass this explicitly whenever `text` doesn't start with the
   * actual title.
   */
  redditTitle?: string;
  label?: string;
  variant?: 'outline' | 'default';
  layout?: 'dropdown' | 'row';
  /** Fired when any share option is chosen -- e.g. for funnel tracking. */
  onShare?: (platform: 'x' | 'linkedin' | 'reddit' | 'copy_link') => void;
}) {
  const [copied, setCopied] = useState(false);

  const targets: ShareTarget[] = [
    {
      key: 'x',
      label: 'Share on X',
      icon: XIcon,
      href: `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`,
    },
    {
      key: 'linkedin',
      label: 'Share on LinkedIn',
      icon: LinkedInIcon,
      href: `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`,
    },
    {
      key: 'reddit',
      label: 'Share on Reddit',
      icon: RedditIcon,
      href: `https://www.reddit.com/submit?url=${encodeURIComponent(url)}&title=${encodeURIComponent(redditTitle ?? text.split('\n')[0])}`,
    },
  ];

  async function copyLink() {
    try {
      await navigator.clipboard.writeText(url);
      setCopied(true);
      toast.success('Link copied');
      onShare?.('copy_link');
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error('Could not copy link');
    }
  }

  if (layout === 'row') {
    return (
      <div className="flex flex-wrap items-center gap-2">
        {targets.map((t) => (
          <Button key={t.key} asChild size="lg" className={cn(
            'h-12 rounded-xl px-5',
            t.key === 'x' ? 'bg-foreground text-background hover:bg-foreground/90' : 'bg-brand text-brand-foreground hover:bg-brand/90'
          )}>
            <a href={t.href} target="_blank" rel="noopener noreferrer" onClick={() => onShare?.(t.key as any)}>
              <t.icon className="mr-2 h-4 w-4" /> {t.label.replace('Share on ', '')}
            </a>
          </Button>
        ))}
        <Button size="lg" variant="outline" className="h-12 rounded-xl px-5" onClick={copyLink}>
          {copied ? <Check className="mr-2 h-4 w-4 text-emerald-500" /> : <Link2 className="mr-2 h-4 w-4" />}
          {copied ? 'Copied' : 'Copy link'}
        </Button>
      </div>
    );
  }

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant={variant} className={variant === 'default' ? 'bg-brand text-brand-foreground hover:bg-brand/90' : ''}>
          <Share2 className="mr-1.5 h-4 w-4" /> {label}
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-48">
        {targets.map((t) => (
          <DropdownMenuItem key={t.key} asChild>
            <a href={t.href} target="_blank" rel="noopener noreferrer" className="flex cursor-pointer items-center gap-2" onClick={() => onShare?.(t.key as any)}>
              <t.icon className="h-4 w-4" /> {t.label}
            </a>
          </DropdownMenuItem>
        ))}
        <DropdownMenuItem onClick={copyLink} className="flex cursor-pointer items-center gap-2">
          {copied ? <Check className="h-4 w-4 text-emerald-500" /> : <Link2 className="h-4 w-4" />} Copy link
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
